### 

@baseURL = http://localhost:3001


### Get all notes

GET {{baseURL}}/api/notes HTTP/1.1
Accept: application/json


### Get note detail

# @prompt noteID

GET {{baseURL}}/api/notes/{{noteID}} HTTP/1.1
Accept: application/json


### Create a new note

POST {{baseURL}}/api/notes HTTP/1.1
Content-Type: application/json

{
  "title": "The new note"
}


### Update the note

# @prompt noteID

PATCH {{baseURL}}/api/notes/{{noteID}} HTTP/1.1
Content-Type: application/json

{
  "title": "Updated note"
}


### Delete note

# @prompt noteID

DELETE {{baseURL}}/api/notes/{{noteID}} HTTP/1.1
